name: Docker Build and Run

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_run:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Uncomment and configure if pushing to Docker Hub
    # - name: Login to DockerHub
    #   uses: docker/login-action@v2
    #   with:
    #     username: ${{ secrets.DOCKER_USERNAME }}
    #     password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: docker build -t springboot-gym-html-app:latest .

    - name: Run Docker container
      run: |
        docker run -d -p 8080:8080 --name springboot-gym-html-app springboot-gym-html-app:latest
        sleep 10
        curl -f http://localhost:8080/ || exit 1
        docker logs springboot-gym-html-app

    - name: Stop and remove container
      if: always()
      run: |
        docker stop springboot-gym-html-app
        docker rm springboot-gym-html-app
