name: Build and Run Spring Boot App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: mvn clean install
        shell: cmd

      - name: Run Spring Boot app
        run: java -jar target\springboot-gym-html-app-1.0.0.jar
        shell: cmd

    # You can simulate post build success/failure using the job outputs or simply add an additional step
    # Here is a simple approach with a success message step:
      - name: Success message
        if: success()
        run: echo "✅ Spring Boot app is running locally!"
        shell: cmd

      - name: Failure message
        if: failure()
        run: echo "❌ Build failed!"
        shell: cmd
